### ISSUE TITLE
Add to favorites is not working as expected. 

### ISSUE THREAD

**Issue by agabaandre** [agabaandre/knowledge_hub#20]
Severity: Warning

Message: Undefined property: stdClass::$id

Filename: models/Publications_model.php

Line Number: 269

Backtrace:

File: C:\xampp\htdocs\knowledge_hub\application\modules\publications\models\Publications_model.php
Line: 269
Function: _error_handler

File: C:\xampp\htdocs\knowledge_hub\application\modules\publications\controllers\Publications.php
Line: 214
Function: save_favourite

File: C:\xampp\htdocs\knowledge_hub\index.php
Line: 139
Function: require_once

**Comment by paulobunga** [comment]
Caught this issue as well during UAT. Can solve it though
